Update keep_serv00.yml

diff --git a/.github/workflows/keep_serv00.yml b/.github/workflows/keep_serv00.yml
--- a/.github/workflows/keep_serv00.yml
+++ b/.github/workflows/keep_serv00.yml
@@ -95,20 +95,17 @@ jobs:
            }
            
           sshpass -p "${{ env.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no -T ${{ env.SERVER_USERNAME }}@${{ env.SERVER_HOSTNAME }} 2>/dev/null << EOF
-            # set -e 
-            # curl -Ls https://raw.githubusercontent.com/co2f2e/Serv00/main/bash/keep_serv00.sh -o keep_serv00.sh || { echo 'Script download failed'; exit 1; }
-            # bash keep_serv00.sh "${{ env.UDPPORT }}" "${{ env.UUID }}" || { echo 'Script execution failed'; exit 1; }
-            # if [ $? -eq 0 ]; then
-              # echo
-              # echo -e "\033[32mSuccess\033[0m"
-              # echo
-            # else
-              # echo
-              # echo -e "\033[31mFailure\033[0m"
-              # echo
-              # exit 1
-            # fi
-            set +e
-            curl -Ls https://raw.githubusercontent.com/co2f2e/Serv00/main/bash/init.sh -o init.sh || { echo 'Script download failed'; exit 1; }
-            bash init.sh
+            set -e 
+            curl -Ls https://raw.githubusercontent.com/co2f2e/Serv00/main/bash/keep_serv00.sh -o keep_serv00.sh || { echo 'Script download failed'; exit 1; }
+            bash keep_serv00.sh "${{ env.UDPPORT }}" "${{ env.UUID }}" || { echo 'Script execution failed'; exit 1; }
+            if [ $? -eq 0 ]; then
+              echo
+              echo -e "\033[32mSuccess\033[0m"
+              echo
+            else
+              echo
+              echo -e "\033[31mFailure\033[0m"
+              echo
+              exit 1
+            fi
           EOF
