Update and rename uninstall_singbox.yml to singbox_uninstall.yml

diff --git a/.github/workflows/singbox_uninstall.yml b/.github/workflows/singbox_uninstall.yml
--- a/.github/workflows/singbox_uninstall.yml
+++ b/.github/workflows/singbox_uninstall.yml
@@ -1,10 +1,10 @@
-name: uninstall_singbox
+name: singbox_uninstall
 
 on:
   workflow_dispatch:  # 支持手动执行  
 
 jobs:
-  unistall_singbox:
+  singbox_uninstall:
     runs-on: ubuntu-latest
 
     strategy:
@@ -94,17 +94,7 @@ jobs:
            
           sshpass -p "${{ env.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no -T ${{ env.SERVER_USERNAME }}@${{ env.SERVER_HOSTNAME }} 2>/dev/null << EOF
             set -e 
-            curl -Ls https://raw.githubusercontent.com/co2f2e/Serv00/main/bash/uninstall_singbox.sh -o uninstall_singbox.sh || { echo 'Script download failed'; exit 1; }
-            bash uninstall_singbox.sh || { echo 'Script execution failed'; exit 1; }
-            cat uninstall_singbox.sh
-            if [ $? -eq 0 ]; then
-              echo
-              echo -e "\033[32mSuccess\033[0m"
-              echo
-            else
-              echo
-              echo -e "\033[31mFailure\033[0m"
-              echo
-              exit 1
-            fi
+            curl -Ls https://raw.githubusercontent.com/co2f2e/Serv00/main/bash/singbox_uninstall.sh -o singbox_uninstall.sh || { echo 'Script download failed'; exit 1; }
+            bash singbox_uninstall.sh || { echo 'Script execution failed'; exit 1; }
+            cat singbox_uninstall.sh
           EOF
