Update uninstall_singbox.yml

diff --git a/.github/workflows/uninstall_singbox.yml b/.github/workflows/uninstall_singbox.yml
--- a/.github/workflows/uninstall_singbox.yml
+++ b/.github/workflows/uninstall_singbox.yml
@@ -94,8 +94,9 @@ jobs:
            
           sshpass -p "${{ env.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no -T ${{ env.SERVER_USERNAME }}@${{ env.SERVER_HOSTNAME }} 2>/dev/null << EOF
             set -e 
-            curl -Ls https://raw.githubusercontent.com/co2f2e/Serv00/main/bash/uninstall_singbox -o uninstall_singbox || { echo 'Script download failed'; exit 1; }
-            bash uninstall_singbox || { echo 'Script execution failed'; exit 1; }
+            curl -Ls https://raw.githubusercontent.com/co2f2e/Serv00/main/bash/uninstall_singbox.sh -o uninstall_singbox.sh || { echo 'Script download failed'; exit 1; }
+            bash uninstall_singbox.sh || { echo 'Script execution failed'; exit 1; }
+            cat uninstall_singbox.sh
             if [ $? -eq 0 ]; then
               echo
               echo -e "\033[32mSuccess\033[0m"
